include: package:lints/recommended.yaml

analyzer:
  language:
    strict-casts: false
    strict-inference: true
    strict-raw-types: true
  errors:
    todo: false

linter:
  rules:
    slash_for_doc_comments: false
    constant_identifier_names: false
    non_constant_identifier_names: false
