include: package:pedantic/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: true
    implicit-dynamic: false
  errors:
    todo: false
    implicit_dynamic_map_literal: false

linter:
  rules:
    slash_for_doc_comments: false
    prefer_final_locals: true
